import {
  MetricCard,
  RecentOrder,
  TopProduct,
  CampaignPerformance,
  AIRecommendation,
  ReviewItem,
  ReviewAnalysis,
  CompetitorData,
  CompetitorAnalysis,
  KeywordResearch,
  KeywordData,
  ReportData,
} from "./types"

export const metricCards: MetricCard[] = [
  {
    label: "Total Revenue",
    value: "$48,592",
    change: 12.5,
    changeLabel: "vs last month",
    icon: "DollarSign",
    trend: "up",
  },
  {
    label: "Total Orders",
    value: "1,284",
    change: 8.2,
    changeLabel: "vs last month",
    icon: "ShoppingCart",
    trend: "up",
  },
  {
    label: "ACOS",
    value: "18.5%",
    change: -2.1,
    changeLabel: "vs last month",
    icon: "Target",
    trend: "down",
  },
  {
    label: "ROAS",
    value: "5.4x",
    change: 15.3,
    changeLabel: "vs last month",
    icon: "TrendingUp",
    trend: "up",
  },
  {
    label: "CTR",
    value: "0.42%",
    change: 0.05,
    changeLabel: "vs last month",
    icon: "MousePointerClick",
    trend: "up",
  },
  {
    label: "CVR",
    value: "12.8%",
    change: -0.3,
    changeLabel: "vs last month",
    icon: "Percent",
    trend: "down",
  },
  {
    label: "Review Rating",
    value: "4.7",
    change: 0.1,
    changeLabel: "vs last month",
    icon: "Star",
    trend: "up",
  },
  {
    label: "Inventory",
    value: "3,420",
    change: -5.2,
    changeLabel: "units remaining",
    icon: "Package",
    trend: "down",
  },
]

export const salesChartData = [
  { date: "Jul 1", revenue: 6200, orders: 178, adSpend: 980 },
  { date: "Jul 2", revenue: 5800, orders: 165, adSpend: 920 },
  { date: "Jul 3", revenue: 7100, orders: 192, adSpend: 1050 },
  { date: "Jul 4", revenue: 5400, orders: 155, adSpend: 870 },
  { date: "Jul 5", revenue: 6900, orders: 185, adSpend: 1020 },
  { date: "Jul 6", revenue: 7500, orders: 210, adSpend: 1150 },
  { date: "Jul 7", revenue: 8100, orders: 228, adSpend: 1200 },
  { date: "Jul 8", revenue: 7200, orders: 198, adSpend: 1080 },
  { date: "Jul 9", revenue: 6500, orders: 182, adSpend: 990 },
  { date: "Jul 10", revenue: 7800, orders: 215, adSpend: 1180 },
  { date: "Jul 11", revenue: 8200, orders: 232, adSpend: 1250 },
  { date: "Jul 12", revenue: 6800, orders: 190, adSpend: 1050 },
  { date: "Jul 13", revenue: 7600, orders: 208, adSpend: 1120 },
  { date: "Jul 14", revenue: 8400, orders: 240, adSpend: 1300 },
]

export const recentOrders: RecentOrder[] = [
  {
    id: "#AMZ-3847",
    product: "Wireless Earbuds Pro",
    asin: "B09XYZ123A",
    price: 49.99,
    status: "delivered",
    date: "2026-07-14",
    customer: "John D.",
  },
  {
    id: "#AMZ-3848",
    product: "Yoga Mat Premium",
    asin: "B08ABC456B",
    price: 29.99,
    status: "pending",
    date: "2026-07-14",
    customer: "Sarah M.",
  },
  {
    id: "#AMZ-3849",
    product: "Stainless Steel Water Bottle",
    asin: "B07DEF789C",
    price: 24.99,
    status: "delivered",
    date: "2026-07-13",
    customer: "Mike R.",
  },
  {
    id: "#AMZ-3850",
    product: "LED Desk Lamp",
    asin: "B06GHI012D",
    price: 39.99,
    status: "cancelled",
    date: "2026-07-13",
    customer: "Emily K.",
  },
  {
    id: "#AMZ-3851",
    product: "Wireless Earbuds Pro",
    asin: "B09XYZ123A",
    price: 49.99,
    status: "delivered",
    date: "2026-07-12",
    customer: "David L.",
  },
]

export const topProducts: TopProduct[] = [
  { name: "Wireless Earbuds Pro", asin: "B09XYZ123A", sales: 342, revenue: 17065.58, growth: 18.5, stock: 520 },
  { name: "Yoga Mat Premium", asin: "B08ABC456B", sales: 256, revenue: 7677.44, growth: 12.3, stock: 340 },
  { name: "Stainless Steel Water Bottle", asin: "B07DEF789C", sales: 198, revenue: 4948.02, growth: -2.1, stock: 180 },
  { name: "LED Desk Lamp", asin: "B06GHI012D", sales: 165, revenue: 6598.35, growth: 8.7, stock: 420 },
  { name: "Portable Charger 20000mAh", asin: "B05JKL345E", sales: 143, revenue: 4285.71, growth: -5.4, stock: 95 },
]

export const campaignPerformance: CampaignPerformance[] = [
  {
    name: "Wireless Earbuds — Main",
    spend: 2840,
    sales: 15620,
    acos: 18.2,
    roas: 5.5,
    impressions: 145200,
    clicks: 2840,
    ctr: 1.96,
  },
  {
    name: "Yoga Mat — Broad",
    spend: 1520,
    sales: 6840,
    acos: 22.2,
    roas: 4.5,
    impressions: 98200,
    clicks: 1680,
    ctr: 1.71,
  },
  {
    name: "Water Bottle — Exact",
    spend: 980,
    sales: 5210,
    acos: 18.8,
    roas: 5.3,
    impressions: 56400,
    clicks: 920,
    ctr: 1.63,
  },
  {
    name: "Desk Lamp — Auto",
    spend: 1240,
    sales: 4980,
    acos: 24.9,
    roas: 4.0,
    impressions: 87200,
    clicks: 1320,
    ctr: 1.51,
  },
]

export const aiRecommendations: AIRecommendation[] = [
  {
    id: "rec-1",
    type: "opportunity",
    title: "Increase bid on 'wireless earbuds' keyword",
    description: "This keyword has a 12.8% CVR and low ACOS. Increasing bid by 20% could generate $2,500 additional monthly revenue.",
    action: "Adjust bid now",
  },
  {
    id: "rec-2",
    type: "warning",
    title: "Portable Charger stock is running low",
    description: "Current inventory of 95 units is projected to last 9 days at current sales velocity. Consider restocking.",
    action: "View inventory plan",
  },
  {
    id: "rec-3",
    type: "suggestion",
    title: "Optimize Yoga Mat Premium listing",
    description: "Listing score is 72/100. Adding 3 missing keywords could improve organic ranking by an estimated 15%.",
    action: "Go to AI Listing",
  },
  {
    id: "rec-4",
    type: "alert",
    title: "2 new negative reviews need attention",
    description: "Reviews mention 'battery life' and 'connectivity'. Addressing these could prevent further rating drop.",
    action: "View reviews",
  },
  {
    id: "rec-5",
    type: "opportunity",
    title: "Keyword opportunity: 'noise cancelling earbuds'",
    description: "Search volume up 45% this month with medium competition. Your product isn't ranking for it yet.",
    action: "Research keyword",
  },
]

export const mockReviews: ReviewItem[] = [
  {
    id: "rv-1",
    rating: 5,
    title: "Best earbuds I've ever owned",
    content: "The sound quality is incredible. Battery lasts all day and the noise cancelling is top-notch. Highly recommend!",
    author: "Mike R.",
    date: "2026-07-12",
    verified: true,
    helpful: 128,
  },
  {
    id: "rv-2",
    rating: 4,
    title: "Great but could improve battery",
    content: "Overall great product. Sound is clear and bass is rich. Only complaint is battery life could be longer — I get about 5 hours.",
    author: "Sarah K.",
    date: "2026-07-10",
    verified: true,
    helpful: 56,
  },
  {
    id: "rv-3",
    rating: 2,
    title: "Connectivity issues",
    content: "These keep disconnecting from my phone. I've tried resetting multiple times but the problem persists. Disappointed for the price.",
    author: "James T.",
    date: "2026-07-08",
    verified: true,
    helpful: 34,
  },
  {
    id: "rv-4",
    rating: 5,
    title: "Perfect for workouts",
    content: "I use these at the gym every day. They stay in place, are sweat resistant, and the sound quality is amazing.",
    author: "Lisa M.",
    date: "2026-07-07",
    verified: true,
    helpful: 89,
  },
  {
    id: "rv-5",
    rating: 3,
    title: "Decent but overpriced",
    content: "They're good earbuds but I think they're a bit overpriced compared to competitors. Case design is nice though.",
    author: "Robert P.",
    date: "2026-07-05",
    verified: false,
    helpful: 22,
  },
  {
    id: "rv-6",
    rating: 1,
    title: "Stopped working after 2 weeks",
    content: "Left earbud completely stopped working after just two weeks. Very disappointed with the quality control.",
    author: "Amanda W.",
    date: "2026-07-03",
    verified: true,
    helpful: 67,
  },
  {
    id: "rv-7",
    rating: 5,
    title: "Excellent customer service",
    content: "Had a small issue and their support team resolved it immediately. Great product and even better service!",
    author: "Chris D.",
    date: "2026-07-02",
    verified: true,
    helpful: 45,
  },
  {
    id: "rv-8",
    rating: 4,
    title: "Good value for money",
    content: "Compared to AirPods, these are much better value. Sound quality is comparable and they're more comfortable.",
    author: "Jennifer L.",
    date: "2026-07-01",
    verified: true,
    helpful: 93,
  },
]

export const reviewAnalysis: ReviewAnalysis = {
  sentiment: {
    positive: 62,
    negative: 18,
    neutral: 20,
  },
  topKeywords: [
    { word: "sound quality", count: 45 },
    { word: "battery", count: 38 },
    { word: "comfort", count: 32 },
    { word: "noise cancelling", count: 28 },
    { word: "connectivity", count: 22 },
    { word: "price", count: 20 },
    { word: "case", count: 18 },
    { word: "workout", count: 15 },
    { word: "customer service", count: 12 },
    { word: "Bluetooth", count: 10 },
  ],
  topPhrases: [
    { phrase: "great sound quality", count: 28, sentiment: "positive" },
    { phrase: "battery life could be better", count: 15, sentiment: "negative" },
    { phrase: "very comfortable to wear", count: 22, sentiment: "positive" },
    { phrase: "keeps disconnecting", count: 12, sentiment: "negative" },
    { phrase: "good value for money", count: 18, sentiment: "positive" },
    { phrase: "stopped working", count: 8, sentiment: "negative" },
    { phrase: "excellent customer service", count: 14, sentiment: "positive" },
    { phrase: "a bit overpriced", count: 10, sentiment: "negative" },
  ],
  painPoints: [
    "Battery life shorter than advertised",
    "Bluetooth connectivity drops frequently",
    "Left earbud quality control issues",
    "Price point concerns vs competitors",
  ],
  mostMentionedFeatures: [
    "Sound Quality",
    "Battery Life",
    "Noise Cancelling",
    "Comfort & Fit",
    "Charging Case",
    "Bluetooth Range",
  ],
  improvementSuggestions: [
    "Improve battery capacity or optimize power consumption",
    "Address Bluetooth chip firmware issues in next update",
    "Strengthen QC for left earbud manufacturing",
    "Consider a price promotion to match competitor positioning",
    "Add quick-start guide to reduce connectivity setup friction",
  ],
  summary: "Overall customer sentiment is positive (62%) with strong appreciation for sound quality and comfort. Key areas for improvement are battery life consistency and Bluetooth connectivity stability. Addressing these two issues could lift the average rating from 4.2 to an estimated 4.5+.",
}

export const competitorData: CompetitorData[] = [
  {
    name: "SoundPro Earbuds X",
    price: 59.99,
    rating: 4.5,
    reviewCount: 2840,
    sellingPoints: ["ANC 2.0", "40hr battery", "Wireless charging"],
    keywordCoverage: 85,
    strengths: ["Brand recognition", "Battery life", "Marketing budget"],
    weaknesses: ["Higher price", "Bulky design", "Average comfort"],
  },
  {
    name: "AudioMax Pro",
    price: 39.99,
    rating: 4.2,
    reviewCount: 1520,
    sellingPoints: ["Budget-friendly", "Good bass", "Compact case"],
    keywordCoverage: 62,
    strengths: ["Price point", "Bass quality", "Portability"],
    weaknesses: ["No ANC", "Plastic build", "Short battery"],
  },
  {
    name: "EliteBuds Ultra",
    price: 79.99,
    rating: 4.6,
    reviewCount: 4100,
    sellingPoints: ["Premium ANC", "Hi-Res audio", "Multipoint connect"],
    keywordCoverage: 92,
    strengths: ["Sound quality", "Build quality", "Feature set"],
    weaknesses: ["Premium price", "Complex app", "Heavy"],
  },
]

export const competitorAnalysis: CompetitorAnalysis = {
  competitors: competitorData,
  priceComparison: [
    { name: "Your Product", price: 49.99 },
    { name: "SoundPro X", price: 59.99 },
    { name: "AudioMax Pro", price: 39.99 },
    { name: "EliteBuds Ultra", price: 79.99 },
  ],
  ratingComparison: [
    { name: "Your Product", rating: 4.7 },
    { name: "SoundPro X", rating: 4.5 },
    { name: "AudioMax Pro", rating: 4.2 },
    { name: "EliteBuds Ultra", rating: 4.6 },
  ],
  keywordOverlap: [
    { keyword: "wireless earbuds", coverage: 78 },
    { keyword: "noise cancelling", coverage: 65 },
    { keyword: "bluetooth earphones", coverage: 82 },
    { keyword: "sports earbuds", coverage: 45 },
    { keyword: "premium audio", coverage: 58 },
    { keyword: "long battery", coverage: 70 },
    { keyword: "gift for him", coverage: 32 },
  ],
  swot: {
    strengths: ["Competitive pricing", "Growing review base", "Better CVR than average", "Strong organic ranking on 12 keywords"],
    weaknesses: ["Lower brand recognition", "Smaller marketing budget", "Limited product line", "Some QC issues reported"],
    opportunities: ["Noise cancelling segment growing 45%", "Holiday season approaching", "Competitor stock issues reported", "Influencer partnership potential"],
    threats: ["SoundPro launching new model in Q4", "Price war in mid-range segment", "Amazon policy changes on review aggregation", "Component cost increases"],
  },
  suggestions: [
    "Target price gap between AudioMax and SoundPro with improved features",
    "Focus keyword strategy on underserved 'sports earbuds' category (45% coverage)",
    "Build review velocity to narrow gap with EliteBuds Ultra (4,100 reviews)",
    "Differentiate on comfort and battery life where competitors are weakest",
    "Prepare holiday promotion strategy now to counter SoundPro Q4 launch",
  ],
}

export const keywordResearch: KeywordResearch = {
  seedKeyword: "wireless earbuds",
  keywords: [
    { keyword: "wireless earbuds bluetooth", searchVolume: 125000, competition: "High", opportunityScore: 65, cpc: 1.85, trend: "up" },
    { keyword: "noise cancelling earbuds", searchVolume: 85000, competition: "High", opportunityScore: 72, cpc: 2.1, trend: "up" },
    { keyword: "wireless earbuds for running", searchVolume: 45000, competition: "Medium", opportunityScore: 85, cpc: 1.45, trend: "up" },
    { keyword: "best budget wireless earbuds", searchVolume: 38000, competition: "Medium", opportunityScore: 78, cpc: 1.25, trend: "stable" },
    { keyword: "wireless earbuds with microphone", searchVolume: 32000, competition: "Medium", opportunityScore: 70, cpc: 1.55, trend: "stable" },
    { keyword: "earbuds for small ears", searchVolume: 28000, competition: "Low", opportunityScore: 92, cpc: 0.95, trend: "up" },
    { keyword: "wireless earbuds long battery life", searchVolume: 25000, competition: "Medium", opportunityScore: 74, cpc: 1.35, trend: "up" },
    { keyword: "earbuds for zoom calls", searchVolume: 22000, competition: "Low", opportunityScore: 88, cpc: 1.15, trend: "up" },
    { keyword: "waterproof wireless earbuds", searchVolume: 20000, competition: "Medium", opportunityScore: 76, cpc: 1.4, trend: "stable" },
    { keyword: "wireless earbuds under $50", searchVolume: 18000, competition: "High", opportunityScore: 60, cpc: 1.6, trend: "stable" },
    { keyword: "earbuds with good bass", searchVolume: 15000, competition: "Low", opportunityScore: 90, cpc: 0.85, trend: "up" },
    { keyword: "gaming wireless earbuds", searchVolume: 12000, competition: "Medium", opportunityScore: 80, cpc: 1.3, trend: "up" },
  ],
  longTailKeywords: [
    "best wireless earbuds for running in rain",
    "noise cancelling earbuds for open office",
    "wireless earbuds that stay in small ears",
    "cheapest wireless earbuds with good microphone for calls",
    "bluetooth earbuds with longest battery life 2026",
  ],
  intentAnalysis: {
    informational: 35,
    navigational: 15,
    commercial: 30,
    transactional: 20,
  },
  seoSuggestions: [
    "Target 'earbuds for small ears' — very low competition, high opportunity score of 92",
    "Create content around 'earbuds with good bass' to capture informational traffic",
    "Optimize listing title to include 'noise cancelling' and 'long battery life'",
    "Add 'waterproof' and 'for running' to back-end search terms",
    "Build a comparison guide targeting 'best budget wireless earbuds' search intent",
  ],
}

export const reportsData: ReportData[] = [
  {
    type: "daily",
    generatedAt: "2026-07-14T08:00:00Z",
    period: "Jul 14, 2026",
    summary: "Strong revenue day driven by increased ad performance. Wireless Earbuds Pro continues to be the top performer with 28 orders. Minor dip in CVR needs monitoring.",
    metrics: {
      revenue: 6840,
      orders: 192,
      acos: 17.8,
      roas: 5.6,
      reviewRating: 4.7,
      topProduct: "Wireless Earbuds Pro",
    },
    highlights: [
      "Revenue up 8.5% vs yesterday",
      "Ad ACOS improved to 17.8% (best this week)",
      "2 new 5-star reviews received",
      "Keyword ranking improved for 'wireless earbuds' — now position #4",
    ],
    recommendations: [
      "Continue current bid strategy — ACOS is healthy",
      "Monitor Portable Charger inventory (95 units left)",
      "Check listing optimization for Yoga Mat (score dropped to 72)",
    ],
  },
  {
    type: "weekly",
    generatedAt: "2026-07-14T08:00:00Z",
    period: "Jul 8 – Jul 14, 2026",
    summary: "Weekly revenue of $48,592 across 1,284 orders. ROAS improved to 5.4x, driven by campaign optimization. Review rating steady at 4.7. Top performer: Wireless Earbuds Pro ($17,066 revenue).",
    metrics: {
      revenue: 48592,
      orders: 1284,
      acos: 18.5,
      roas: 5.4,
      reviewRating: 4.7,
      topProduct: "Wireless Earbuds Pro",
    },
    highlights: [
      "Revenue exceeded target by 7%",
      "ROAS improved from 4.8x to 5.4x week-over-week",
      "Campaign optimization reduced wasted spend by $320",
      "12 new reviews (avg rating 4.5)",
      "Organic ranking improved on 8 keywords",
    ],
    recommendations: [
      "Scale Wireless Earbuds Pro campaign — ROAS supports higher spend",
      "Address negative review themes: battery & connectivity",
      "Prepare Q3 promotion calendar",
      "Consider restocking Portable Charger before stockout",
    ],
  },
  {
    type: "monthly",
    generatedAt: "2026-07-14T08:00:00Z",
    period: "July 2026 (MTD)",
    summary: "Month-to-date revenue of $195,400 with solid ROAS of 5.4x. Account health is excellent with 4.7 star average rating. Key growth drivers: campaign optimization and organic ranking improvements.",
    metrics: {
      revenue: 195400,
      orders: 5136,
      acos: 18.2,
      roas: 5.5,
      reviewRating: 4.7,
      topProduct: "Wireless Earbuds Pro",
    },
    highlights: [
      "MTD revenue tracking 15% above same period last month",
      "Campaign ACOS improved from 21% to 18.2%",
      "Review count grew by 48 (85% 4-5 star)",
      "Launched 2 new product variations",
      "Competitor keyword gap narrowed by 12%",
    ],
    recommendations: [
      "Allocate additional 20% budget to top-performing campaigns",
      "Develop Q4 holiday strategy starting August",
      "Expand product line based on keyword opportunity analysis",
      "Build influencer outreach program for product seeding",
    ],
  },
]
